server.port: 8110
tg.username: shoponline_test_bot
tg.token: 5834394816:AAEqjbg0upLgyLwOBYEm3VDPyxy0zZL139o
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"